services:
  user-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=your_secret_key
      - USER_SERVICE_URL=http://user-service:3000
    command: ["node", "user-service/userServer.js"]
    depends_on:
      - mongo

  ride-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ride-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - RIDE_SERVICE_URL=http://ride-service:4000
      - MONGO_URI=mongodb://mongo:27017/Uber_ride
      - DRIVER_LOCATION_SERVICE_URL=http://driver-location-service:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["node", "ride-service/rideServer.js"]
    depends_on:
      - mongo
      - user-service

  driver-location-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: driver-location-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["node", "driver-location-service/driverLocationServer.js"]
    depends_on:
      - redis

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongo_data:
